name: test
on: [pull_request,workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Bundle install
        run: |
          gem install bundler
          bundle
      - name: Run RSpec
        run: bundle exec rspec